### PR TITLE
Nox Hands can bypass an iris if allowed in cap config

### PR DESCRIPTION
**Pull request by Matspyder51**
Nox & Tollans can pass through SGC iris, since creating a weapon only for this seem unrevelant, I set it to nox hands SWEP
Enabled by default in config since on most servers, this SWEP is disabled for non-admin by default

### CODE REVIEW

**Comment by Hawkfang42** [comment]
I tried CAP with this commit (and one other) but it leaves you stuck where the iris is, could you possibly find a way for it to instead open the iris or teleport you further?

**Comment by AlexALX** [comment]
merging this, but will disable by default

**Comment by Hawkfang42** [comment]
Wait, is this in the workshop version yet?

**Comment by AlexALX** [comment]
Nope, there is workshop changes incoming in this month so need to wait a bit.

**Pull request merged**
