### PR TITLE
Added check for an 'Unblockable' variable.

### PR DESCRIPTION
**Pull request by 2000Slash**
When an entity has it set to true, the entity wont block the Stargate from opening when placed in front of it.

### CODE REVIEW

**Comment by 2000Slash** [comment]
No problem it's a special case. I'm trying to make a StarGate to another map and place an Entity directly against the Gate, that saves the map I'm playing in a file and then changes to another Map. There is probably a better way of doing it by creating a fake StarGate that just changes the level when I go through it but I am not that good in lua.

**Comment by TheMerkyShadow** [comment]
@2000Slash I think there might already be one 

Look at line 1357.

if (only_block and self.DialBlocked) then return false end

**Comment by 2000Slash** [comment]
I am not sure if I understood that code exactly, because shouldn't I then have to override the dial function that calls the ENT:IsBlocked function? Because I'd rather have it working with the normal StarGates.

**Comment by TheMerkyShadow** [comment]
What i'm saying is that you can disable it entirely for everything that would temporarily fix your problem.

**Comment by 2000Slash** [comment]
Oh my bad, I know what you meant but didn't see it In-game. But thanks for your help anyways.

**Pull request closed without merging**
