### PR TITLE
Wire Output and Door control panel

### PR DESCRIPTION
**Pull request by Matspyder51**
I have add the two panels (Goauld and Ori) to Door Control Panel
I have add a Driver [Entity] WireOutput to get the driver of a Jumper (Maybe add this to other ships ?)

My apologize if my english not good.

### CODE REVIEW

**Comment by AlexALX** [comment]
Everything i ok except new models spawning at wrong angles on cap door itself.

list.Set(TOOL.List,"models/madman07/ring_panel/goauld_panel.mdl",{});

should be taken for example from controlpanel.lua
list.Set(TOOL.List,"models/madman07/ring_panel/goauld_panel.mdl",{Angle=Angle(270,0,0),Position=Vector(0,0,-12)});

and all model paths should be lowercases or this parameters not work.

Also in your case why also not add ancient panel? And if really, there is separated control panel for those things with buttons and you can code them lik you want. So really don't know if this actually needed, but i still can add this.

Ok i'll merge with some fixes. Thank you.

**Comment by AlexALX** [comment]
[ERROR] addons/cap/lua/entities/puddle_jumper/init.lua:414: attempt to call method 'setWire' (a nil value)
  1. unknown - addons/cap/lua/entities/puddle_jumper/init.lua:414

SetWire not setWire.

**Comment by Matspyder51** [comment]
I could not test the jumper modification because it's require modifications, and I did not have the cap_ressources from github, I downloaded last night, now I can test.
For panels, I have test on a server.
About lua, I'm new in this language, usualy, I develop in Web language, so if I have made mistakes, I'm sorry, I have change setWire -> SetWire and set Input to "nil" when Driver left the jumper, so if you wan't that change, I can create an other pull request.

**Comment by AlexALX** [comment]
I already commited it and did all required fixes: https://github.com/RafaelDeJongh/cap/commit/dff2d38415559910d7b6b19d010e06999ff6ffab

**Comment by AlexALX** [comment]
Also you don't require have cap_resources from github for use cap code github part. Cap code can work fine with workshop resources except cap code workshop part.

**Comment by Matspyder51** [comment]
Yes, but if I paste cap folder to my addons folder, I need to Uninstall/Desactivate Workshop Addons and if I do it, I don't have models ... right ?

**Comment by AlexALX** [comment]
You need only deactivate CAP: Code part and install cap code from github, thats all.

**Pull request merged**
