### PR TITLE
Added open/close by right-clicking

### PR DESCRIPTION
**Pull request by CryptAlchemy**
The staff weapons in the Stargate TV series were able to open and close.
I have added this feature.

### CODE REVIEW

**Comment by CryptAlchemy** [comment]
Any time now guys...

**Comment by AlexALX** [comment]
Soon, i just need finish some things before make new cap version.

**Comment by CryptAlchemy** [comment]
Sounds good.

**Comment by AlexALX** [comment]
currently delay is due to workshop resources cannot be updated without rafael, i still remember about this.

**Comment by CryptAlchemy** [comment]
Sounds good

**Comment by AlexALX** [comment]
Sorry for so long delay, but anyway i want make this in this year))

**Comment by CryptAlchemy** [comment]
It's all good, better late than never :)

**Pull request merged**
