### PR TITLE
Update for Shield_Generator. (Wire Disable Sound)

### PR DESCRIPTION
**Pull request by KvasirSG**
ever since the http://www.sg-carterpack.com/forums/topic/shield/#post-6382 about the wire sound disable for shields i have been testing it out and found a solution for it here is my result it has been tested in Gmod without any errors or lack of functions

### CODE REVIEW

**Comment by KvasirSG** [comment]
Found an Error doing testing 2 sorry did not see that coming

**Comment by AlexALX** [comment]
Change please variable name to SndDisable or so, because Active can mess with some scripts (not in cap)

**Comment by KvasirSG** [comment]
ohh yeah forgot about that my bad fixing that right away

**Comment by AlexALX** [comment]
Line 111 still Active. ))

**Comment by KvasirSG** [comment]
first time using github else than the clone thing so created a new pull for the fix pull #15 https://github.com/RafaelDeJongh/cap/pull/15

**Pull request closed without merging**
