### PR TITLE
Vehicle Ghosting Bug Workaround.

### PR DESCRIPTION
**Pull request by EssGeeEich**
Vehicle Ghosting Bug Workaround.
In case you need an immediate discussion, please contact me here:
http://steamcommunity.com/id/essgeeeich/

### CODE REVIEW

**Comment by AlexALX** [comment]
This changes will broke compatibility with some cap things what use parent functional for derive keyvalues from parent entity. And as far i know this fixed in gmod dev branch without any code modifications.

**Comment by EssGeeEich** [comment]
An Alternative Fix has been supplied. This seems to be an erroneous behavior from IsValid, and no matter what state the dev branch is in, there is no known ETA. A day, a week, a month... and it's been two weeks already, just for a simple fix.

I'd rather help you getting this sorted out than sitting around, waiting for stuff to fix itself, even if it meant restoring the old code after the patch.

**Comment by X-Coder** [comment]
I reported the issue already to gmod developer a while ago after spending a whole day checking that is not my installation and tracing down all the addons / the sources: https://github.com/Facepunch/garrysmod-issues/issues/2334. I traced it down to the same line you changed in your workaround.

Its fixed in current gmod dev branch already, but as robotboy655 doesn't seem to like talking, no one seems to know what it was / how to fix it until the release / or when it will be released.

"It is one of your addons. This is not a place to get help."
"Problem solved, no need to discuss this any further, expect an update."(robotboy655)
I don't like how robotboy handles some of the bug reports, this are the type of answers which pisses me off. But I'm thankful he does the job, because he seems to be the only one working on gmod sources.

**Comment by AlexALX** [comment]
@EssGeeEich even with new fix you code still comented, anyway going to do few tests and if it work i'll update cap code.

**Pull request merged**
