### PR TITLE
GDO Transmit

### PR DESCRIPTION
**Pull request by TheMerkyShadow**
I think this is a really good idea will allow Stargates to receive GDO code through an already existing transmit and receive system.

### CODE REVIEW

**Comment by viral32111** [comment]
Yes! I hope this gets merged. It will be really useful to automate base building.

**Comment by TheMerkyShadow** [comment]
@viral32111 haha thanks glad someone likes my idea

**Comment by AlexALX** [comment]
Why you want to do like this if you can receive code on iris computer?

**Comment by TheMerkyShadow** [comment]
Yea the Iris computer works fine. However some people like myself want to build there own Iris computers through e2 instead of having to deal with the middle man of the Iris computer. Its just a nice feature I think makes sense and people could use.

**Comment by AlexALX** [comment]
But in this case you will not able to send answer to gdo as this possible only via iris computer, and it will always show error...

**Comment by TheMerkyShadow** [comment]
This is true. I could fix it so that the Gdo's answer doesn't rely on the iris computer but the gate itself.

**Comment by TheMerkyShadow** [comment]
@AlexALX I redid a lot of the GDO to address the issue at hand. 
However, I couldn't help myself as I completely changed the functionality of the GDO's code.
I felt it was extremely over-complicated and felt a strong urge to make it a whole lot simpler. 
If you do not approve of the changes I'll go back and revise it.

**Comment by TheMerkyShadow** [comment]
@AlexALX I've been testing my code through as many different situations as possible to make it as close as I could to the original code. It was hard all things considering since the original code was very bulky. I think I found the best way and I made it a lot more simpler than the original.

**Comment by TheMerkyShadow** [comment]
I can say as of right now that I can't find anything more to add/fix at this moment so this should be final.

**Comment by AlexALX** [comment]
You are did too much changes and broke some features from gdo, replacing all code without really understanding for what it was done like this is really bad idea.

**Comment by AlexALX** [comment]
Everything what i can suggest if someone still want this - is just trigger output with simple checking code on gdo side WHEN there is NO iris computer on another side. Something like this.

**Comment by TheMerkyShadow** [comment]
Ok my bad I was under the impression you hated the idea entirely. I could do that

**Comment by TheMerkyShadow** [comment]
I have to close this pull request and make another one for some strange reason

**Pull request closed without merging**
