### PR TITLE
Fixed SGC screen "enter" key bug.

### PR DESCRIPTION
**Pull request by CryptAlchemy**
Fixed a bug where the enter key would not change the SGC screens in the menu. Now it works :)

### CODE REVIEW

**Comment by AlexALX** [comment]
If key code was changed then its very bad for whole cap, as keycode 13 used in many placed and not only for sgc screen. Lets wait for upcoming gmod update maybe it will be back not sure.

**Comment by AlexALX** [comment]
Ok its not gmod issue, its wiremod update https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_keyboard/remap.lua#L65

so they changed this line and break much of stuff. need some investigation

**Comment by CryptAlchemy** [comment]
Ok sounds good.

**Comment by AlexALX** [comment]
https://github.com/wiremod/wire/issues/1354

**Comment by CryptAlchemy** [comment]
Well it seems that the Wiremod creator will not change it, I guess the only choice is to do the CTRL-F technique.

**Pull request closed without merging**
