### PR TITLE
Updated module stargate_ex.lua to the latest StarfallEx API

### PR DESCRIPTION
**Pull request by F0x06**
Hi, i updated the starfall_ex.lua module to the latest StarfallEx API to follow pull #86.

I think you d'ont need to add specific code to have both legacy and new module, the module will simply fail and wont load.

Thanks.

### CODE REVIEW

**Comment by AlexALX** [comment]
Did you tested with legacy starfall? its still better to have check with nil than having lua error in console with legacy starfall. We should avoid lua errors if this is simple few lines check.

**Comment by F0x06** [comment]
Question, why keeping legacy starfall module ? Things in starfall legacy are broken, and it's unmaintained since 2016. Anyways i tested it and it works, i also added a check to prevent `stargate_ex.lua` to load on legacy Starfall 👍

**Comment by AlexALX** [comment]
not sure, but we have some old starfall chips from cap for it, and idk if they work with new starfall. if its really abandoned then maybe there is sense to remove it, but only if other chips are working on new one.

**Comment by F0x06** [comment]
> not sure, but we have some old starfall chips from cap for it, and idk if they work with new starfall. if its really abandoned then maybe there is sense to remove it, but only if other chips are working on new one.

I understand, maybe you can try if the chips are working with StarfallEx ? I think if you need to adapt the code it will be pretty quick, most of it will be camel case function names :)

**Pull request merged**
